- name: Install Docker daemon for debian distribution
  when: ansible_facts['distribution'] == 'Ubuntu'
  apt:
    name:
    - docker.io
    - docker-buildx
    state: present
    update_cache: yes

- name: Download firecracker binary
  ansible.builtin.shell: |
    set -e
    export CPU_TYPE=$(lscpu |grep "Architecture"| awk -F ":" '{print $2}'|tr -d " ")
    export CPU_ARCH="amd64"


    if [ ${CPU_TYPE} != "x86_64" ];
    then
      export CPU_ARCH="arm64"
    fi
    cd /tmp/
      curl -LO https://github.com/WoodProgrammer/firecracker-rootfs-builder/releases/download/v0.0.2/firecracker-rootfs-builder_0.0.2_linux_${CPU_ARCH}.tar.gz
      tar -xvf firecracker-rootfs-builder_0.0.2_linux_${CPU_ARCH}.tar.gz && mv bin/ofs /usr/local/bin/

      rm -rf bin firecracker-rootfs-builder_0.0.2_linux_${CPU_ARCH}.tar.gz
    cd ..

- name: Upload rootfs OCI config template
  template:
    src: config.yaml.j2
    dest: /tmp/{{config_file_name}}

- name: Build rootfs from OCI image
  ansible.builtin.shell: |
    set -e
    mkdir -p /tmp/{{target_directory}}-builder

    cd /tmp/{{target_directory}}-builder
      ofs -C /tmp/{{config_file_name}}
    cd ..
  register: result